name: Deploy AWS SAM Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install AWS SAM CLI
        run: |
          pip install aws-sam-cli

      - name: Build SAM application
        run: |
          sam build

      - name: Deploy SAM application
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-east-1'
        run: |
          sam deploy --no-confirm-changeset --stack-name crypto-app --capabilities CAPABILITY_IAM --region $AWS_REGION --resolve-s3

      - name: Configure Git
        run: |
          git config --global user.email "arvindbharathy.natarajan97@gmail.com"
          git config --global user.name "arvindn97"

      - name: Tag the deployment
        run: |
          git tag -a "deploy-$(date +'%Y%m%d%H%M%S')" -m "Deployment on $(date +'%Y-%m-%d %H:%M:%S')"
          git push origin --tags
